version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "02:00"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - dependabot
